using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Singularity.DataService.Test.SqlFramework
{
	public class SqlAdministratorMock : SqlAdministrator
	{
		public SqlAdministratorMock(SqlConnection masterSqlConnection) : base(masterSqlConnection)
		{
		}

		protected override String CreateDatabaseQuery => @"CREATE DATABASE [{0}]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'{0}', FILENAME = N'f:\Program Files\Microsoft SQL Server\MSSQL13.FUNKEY\MSSQL\DATA\{0}.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'{0}_log', FILENAME = N'f:\Program Files\Microsoft SQL Server\MSSQL13.FUNKEY\MSSQL\DATA\{0}_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [{0}] SET COMPATIBILITY_LEVEL = 130
GO
ALTER DATABASE [{0}] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [{0}] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [{0}] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [{0}] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [{0}] SET ARITHABORT OFF 
GO
ALTER DATABASE [{0}] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [{0}] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [{0}] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [{0}] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [{0}] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [{0}] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [{0}] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [{0}] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [{0}] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [{0}] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [{0}] SET  DISABLE_BROKER 
GO
ALTER DATABASE [{0}] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO
ALTER DATABASE [{0}] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [{0}] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [{0}] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [{0}] SET  READ_WRITE 
GO
ALTER DATABASE [{0}] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [{0}] SET  MULTI_USER 
GO
ALTER DATABASE [{0}] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [{0}] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [{0}] SET DELAYED_DURABILITY = DISABLED 
GO
USE [{0}]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [{0}] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
";

		protected override String DeleteDatabaseQuery => @"EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'Singularity'
GO
USE [master]
GO
ALTER DATABASE [{0}] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
DROP DATABASE [{0}]
GO
";


	}
}
